/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface":                  "#fdf8f5",
        "surface-dim":              "#ddd9d6",
        "surface-bright":           "#fdf8f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#f7f3ef",
        "surface-container":        "#f2ede9",
        "surface-container-high":   "#ece7e4",
        "surface-container-highest":"#e6e2de",
        "surface-variant":          "#e6e2de",
        "surface-tint":             "#99462a",
        "on-surface":               "#1c1b19",
        "on-surface-variant":       "#55433d",
        "inverse-surface":          "#32302e",
        "inverse-on-surface":       "#f4f0ec",
        "outline":                  "#88726c",
        "outline-variant":          "#dbc1b9",
        "background":               "#fdf8f5",
        "on-background":            "#1c1b19",
        "primary":                  "#99462a",
        "on-primary":               "#ffffff",
        "primary-container":        "#d97757",
        "on-primary-container":     "#541400",
        "inverse-primary":          "#ffb59e",
        "primary-fixed":            "#ffdbd0",
        "primary-fixed-dim":        "#ffb59e",
        "on-primary-fixed":         "#390b00",
        "on-primary-fixed-variant": "#7a2f15",
        "secondary":                "#5f5f58",
        "on-secondary":             "#ffffff",
        "secondary-container":      "#e4e2da",
        "on-secondary-container":   "#65655e",
        "secondary-fixed":          "#e4e2da",
        "secondary-fixed-dim":      "#c8c7bf",
        "on-secondary-fixed":       "#1b1c17",
        "on-secondary-fixed-variant":"#474741",
        "tertiary":                 "#006b5f",
        "on-tertiary":              "#ffffff",
        "tertiary-container":       "#09a493",
        "on-tertiary-container":    "#00312b",
        "tertiary-fixed":           "#7df7e3",
        "tertiary-fixed-dim":       "#5edac7",
        "on-tertiary-fixed":        "#00201c",
        "on-tertiary-fixed-variant":"#005047",
        "error":                    "#ba1a1a",
        "on-error":                 "#ffffff",
        "error-container":          "#ffdad6",
        "on-error-container":       "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm":      "0.25rem",
        "md":      "0.75rem",
        "lg":      "1rem",
        "xl":      "1.5rem",
        "full":    "9999px",
      },
      spacing: {
        "unit":             "4px",
        "stack-sm":         "12px",
        "stack-md":         "24px",
        "stack-lg":         "48px",
        "gutter":           "24px",
        "margin-mobile":    "20px",
        "margin-desktop":   "40px",
        "container-max":    "720px",
      },
      fontFamily: {
        "newsreader": ["Newsreader", "Georgia", "serif"],
        "inter":      ["Inter", "-apple-system", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1",  letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2",  letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3",  fontWeight: "500" }],
        "body-lg":     ["20px", { lineHeight: "1.6",  fontWeight: "400" }],
        "body-md":     ["17px", { lineHeight: "1.6",  fontWeight: "400" }],
        "label-lg":    ["15px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md":    ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-sm":    ["11px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "600" }],
      },
      maxWidth: {
        "reading": "720px",
      },
    },
  },
  plugins: [],
}
